# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'InClass10' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InClass10
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'SDWebImage', '~>3.8'
end
